package com.issuetracker.util;

public class JwtTokenForTest {

	public static final String accessToken = "eyJhbGciOiJIUzM4NCJ9.eyJlbWFpbCI6InVzZXIwMUBnbWFpbC5jb20iLCJtZW1iZXJJZCI6MSwibmlja25hbWUiOiLsnKDsoIAxIiwicHJvZmlsZUltYWdlVXJpIjoiaHR0cHM6Ly9pLmltZ3VyLmNvbS93Q2w4b3NkLnBuZyIsImV4cCI6MjY5MjIzODMxOH0.QtDfPyBTB8rbn7zVlOS-aGKGv8uN6IFedSuDaP_SFlPeSy6fHflY16VXD6HKh6ay";
}
