spring:
  datasource:
    url: jdbc:mysql://localhost:3308/issue-tracker?allowMultiQueries=true
    username: user
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath*:schema.sql
    encoding: UTF-8
  profiles:
    include: oauth

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: codesquad.kr.gyeonggidoidle.issuetracker.domain

jwt:
  secret: Y29kZXNxdWFkLWlzc3VlLXRyYWNrZXItbWF4LTAxLWd5ZW9uZ2dpZG9pZGxl
  access-expiration-milliseconds: 3600000 # 1시간
  refresh-expiration-milliseconds: 5184000000 # 60일
