spring:
  datasource:
    url: ${db.prod.datasource.url}
    username: ${db.prod.datasource.username}
    password: ${db.prod.datasource.password}

  sql:
    init:
      mode: always

cloud:
  aws:
    credentials:
      access-key: ${aws.access-key}
      secret-key: ${aws.secret-key}
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: ${aws.s3.bucket}
